export const PERMISSIONS = {
  PRODUCT_READ: "product.read", PRODUCT_WRITE: "product.write", PRODUCT_APPROVE: "product.approve",
  SUPPLIER_READ: "supplier.read", SUPPLIER_WRITE: "supplier.write", SUPPLIER_QUALIFY: "supplier.qualify",
  LOT_READ: "lot.read", LOT_WRITE: "lot.write", LOT_RELEASE: "lot.release",
  PURCHASE_ORDER_READ: "purchase_order.read", PURCHASE_ORDER_WRITE: "purchase_order.write",
  PAYMENT_AUTHORIZE: "payment.authorize",
  RECEIPT_READ: "receipt.read", RECEIPT_CREATE: "receipt.create",
  DOCUMENT_READ: "document.read", DOCUMENT_UPLOAD: "document.upload", DOCUMENT_VERIFY: "document.verify",
  TEST_READ: "test.read", TEST_WRITE: "test.write", TEST_REVIEW: "test.review",
  INVENTORY_READ: "inventory.read", INVENTORY_ADJUST: "inventory.adjust", INVENTORY_ALLOCATE: "inventory.allocate",
  EXCEPTION_READ: "exception.read", EXCEPTION_CREATE: "exception.create", EXCEPTION_CLOSE: "exception.close",
  ACTION_READ: "action.read", ACTION_WRITE: "action.write", ACTION_COMPLETE: "action.complete",
  CAPA_READ: "capa.read", CAPA_WRITE: "capa.write", CAPA_CLOSE: "capa.close",
  DECISION_READ: "decision.read", DECISION_WRITE: "decision.write", DECISION_APPROVE: "decision.approve",
  ORGANIZATION_READ: "organization.read", ORGANIZATION_WRITE: "organization.write", ORGANIZATION_VERIFY: "organization.verify",
  MARKET_READ: "market.read", MARKET_WRITE: "market.write",
  RESEARCH_READ: "research.read", RESEARCH_WRITE: "research.write",
  INTELLIGENCE_QUERY: "intelligence.query",
  MIGRATION_READ: "migration.read", MIGRATION_RUN: "migration.run", MIGRATION_RESOLVE: "migration.resolve",
  ADMIN_USERS: "admin.users", ADMIN_ROLES: "admin.roles", AUDIT_READ: "admin.audit",
} as const;

export type PermissionKey = typeof PERMISSIONS[keyof typeof PERMISSIONS];

export function requirePermission(userPermissions: Iterable<string>, required: PermissionKey): void {
  const set = userPermissions instanceof Set ? userPermissions : new Set(userPermissions);
  if (!set.has(required)) throw new Error(`FORBIDDEN:${required}`);
}

export function hasPermission(userPermissions: Iterable<string>, required: PermissionKey): boolean {
  const set = userPermissions instanceof Set ? userPermissions : new Set(userPermissions);
  return set.has(required);
}

export const ROLE_PERMISSIONS: Record<string, PermissionKey[]> = {
  FOUNDER: [
    PERMISSIONS.PRODUCT_READ, PERMISSIONS.PRODUCT_WRITE, PERMISSIONS.PRODUCT_APPROVE,
    PERMISSIONS.SUPPLIER_READ, PERMISSIONS.SUPPLIER_WRITE, PERMISSIONS.SUPPLIER_QUALIFY,
    PERMISSIONS.LOT_READ, PERMISSIONS.LOT_WRITE, PERMISSIONS.LOT_RELEASE,
    PERMISSIONS.PURCHASE_ORDER_READ, PERMISSIONS.PURCHASE_ORDER_WRITE, PERMISSIONS.PAYMENT_AUTHORIZE,
    PERMISSIONS.RECEIPT_READ, PERMISSIONS.RECEIPT_CREATE,
    PERMISSIONS.DOCUMENT_READ, PERMISSIONS.DOCUMENT_UPLOAD, PERMISSIONS.DOCUMENT_VERIFY,
    PERMISSIONS.TEST_READ, PERMISSIONS.TEST_WRITE, PERMISSIONS.TEST_REVIEW,
    PERMISSIONS.INVENTORY_READ, PERMISSIONS.INVENTORY_ADJUST, PERMISSIONS.INVENTORY_ALLOCATE,
    PERMISSIONS.EXCEPTION_READ, PERMISSIONS.EXCEPTION_CREATE, PERMISSIONS.EXCEPTION_CLOSE,
    PERMISSIONS.ACTION_READ, PERMISSIONS.ACTION_WRITE, PERMISSIONS.ACTION_COMPLETE,
    PERMISSIONS.CAPA_READ, PERMISSIONS.CAPA_WRITE, PERMISSIONS.CAPA_CLOSE,
    PERMISSIONS.DECISION_READ, PERMISSIONS.DECISION_WRITE, PERMISSIONS.DECISION_APPROVE,
    PERMISSIONS.ORGANIZATION_READ, PERMISSIONS.ORGANIZATION_WRITE, PERMISSIONS.ORGANIZATION_VERIFY,
    PERMISSIONS.MARKET_READ, PERMISSIONS.MARKET_WRITE,
    PERMISSIONS.RESEARCH_READ, PERMISSIONS.RESEARCH_WRITE, PERMISSIONS.INTELLIGENCE_QUERY,
    PERMISSIONS.MIGRATION_READ, PERMISSIONS.MIGRATION_RUN, PERMISSIONS.MIGRATION_RESOLVE,
    PERMISSIONS.ADMIN_USERS, PERMISSIONS.ADMIN_ROLES, PERMISSIONS.AUDIT_READ,
  ],
  SYSTEM_ADMIN: [PERMISSIONS.PRODUCT_READ,PERMISSIONS.SUPPLIER_READ,PERMISSIONS.LOT_READ,PERMISSIONS.PURCHASE_ORDER_READ,PERMISSIONS.RECEIPT_READ,PERMISSIONS.DOCUMENT_READ,PERMISSIONS.TEST_READ,PERMISSIONS.INVENTORY_READ,PERMISSIONS.EXCEPTION_READ,PERMISSIONS.ACTION_READ,PERMISSIONS.CAPA_READ,PERMISSIONS.DECISION_READ,PERMISSIONS.ORGANIZATION_READ,PERMISSIONS.MARKET_READ,PERMISSIONS.RESEARCH_READ,PERMISSIONS.MIGRATION_READ,PERMISSIONS.ADMIN_USERS,PERMISSIONS.ADMIN_ROLES,PERMISSIONS.AUDIT_READ],
  QUALITY_ADMIN: [PERMISSIONS.PRODUCT_READ,PERMISSIONS.PRODUCT_WRITE,PERMISSIONS.SUPPLIER_READ,PERMISSIONS.SUPPLIER_QUALIFY,PERMISSIONS.LOT_READ,PERMISSIONS.LOT_WRITE,PERMISSIONS.LOT_RELEASE,PERMISSIONS.RECEIPT_READ,PERMISSIONS.RECEIPT_CREATE,PERMISSIONS.DOCUMENT_READ,PERMISSIONS.DOCUMENT_UPLOAD,PERMISSIONS.DOCUMENT_VERIFY,PERMISSIONS.TEST_READ,PERMISSIONS.TEST_WRITE,PERMISSIONS.TEST_REVIEW,PERMISSIONS.INVENTORY_READ,PERMISSIONS.INVENTORY_ADJUST,PERMISSIONS.EXCEPTION_READ,PERMISSIONS.EXCEPTION_CREATE,PERMISSIONS.EXCEPTION_CLOSE,PERMISSIONS.ACTION_READ,PERMISSIONS.ACTION_WRITE,PERMISSIONS.ACTION_COMPLETE,PERMISSIONS.CAPA_READ,PERMISSIONS.CAPA_WRITE,PERMISSIONS.CAPA_CLOSE,PERMISSIONS.DECISION_READ,PERMISSIONS.AUDIT_READ],
  OPERATIONS: [PERMISSIONS.PRODUCT_READ,PERMISSIONS.SUPPLIER_READ,PERMISSIONS.LOT_READ,PERMISSIONS.LOT_WRITE,PERMISSIONS.RECEIPT_READ,PERMISSIONS.RECEIPT_CREATE,PERMISSIONS.DOCUMENT_READ,PERMISSIONS.INVENTORY_READ,PERMISSIONS.INVENTORY_ADJUST,PERMISSIONS.INVENTORY_ALLOCATE,PERMISSIONS.EXCEPTION_READ,PERMISSIONS.EXCEPTION_CREATE,PERMISSIONS.ACTION_READ,PERMISSIONS.ACTION_WRITE],
  PROCUREMENT: [PERMISSIONS.PRODUCT_READ,PERMISSIONS.SUPPLIER_READ,PERMISSIONS.SUPPLIER_WRITE,PERMISSIONS.PURCHASE_ORDER_READ,PERMISSIONS.PURCHASE_ORDER_WRITE,PERMISSIONS.DOCUMENT_READ,PERMISSIONS.EXCEPTION_READ,PERMISSIONS.ACTION_READ,PERMISSIONS.ACTION_WRITE],
  COMMERCIAL: [PERMISSIONS.PRODUCT_READ,PERMISSIONS.ORGANIZATION_READ,PERMISSIONS.ORGANIZATION_WRITE,PERMISSIONS.ORGANIZATION_VERIFY,PERMISSIONS.INVENTORY_READ,PERMISSIONS.ACTION_READ],
  RESEARCH_ORII: [PERMISSIONS.PRODUCT_READ,PERMISSIONS.TEST_READ,PERMISSIONS.DOCUMENT_READ,PERMISSIONS.MARKET_READ,PERMISSIONS.MARKET_WRITE,PERMISSIONS.RESEARCH_READ,PERMISSIONS.RESEARCH_WRITE,PERMISSIONS.INTELLIGENCE_QUERY,PERMISSIONS.DECISION_READ],
  AUDITOR: [PERMISSIONS.PRODUCT_READ,PERMISSIONS.SUPPLIER_READ,PERMISSIONS.LOT_READ,PERMISSIONS.PURCHASE_ORDER_READ,PERMISSIONS.RECEIPT_READ,PERMISSIONS.DOCUMENT_READ,PERMISSIONS.TEST_READ,PERMISSIONS.INVENTORY_READ,PERMISSIONS.EXCEPTION_READ,PERMISSIONS.ACTION_READ,PERMISSIONS.CAPA_READ,PERMISSIONS.DECISION_READ,PERMISSIONS.ORGANIZATION_READ,PERMISSIONS.MARKET_READ,PERMISSIONS.RESEARCH_READ,PERMISSIONS.AUDIT_READ],
  AI_ASSISTANT: [PERMISSIONS.PRODUCT_READ,PERMISSIONS.LOT_READ,PERMISSIONS.TEST_READ,PERMISSIONS.DOCUMENT_READ,PERMISSIONS.EXCEPTION_READ,PERMISSIONS.INTELLIGENCE_QUERY],
};
